package com.example.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.components.StatusBadge
import com.example.ui.theme.*

data class SystemReport(
    val id: String,
    val title: String,
    val category: String,
    val date: String,
    val summary: String,
    val fullContent: String
)

@Composable
fun ReportsScreen(
    modifier: Modifier = Modifier
) {
    var selectedReport by remember { mutableStateOf<SystemReport?>(null) }

    val reports = remember {
        listOf(
            SystemReport(
                id = "REP-2026-0924-A",
                title = "Daily Municipal Civic Health & Anomaly Digest",
                category = "CIVIC",
                date = "September 24, 2026",
                summary = "Overview of 24 detected incidents, 18 resolved, AI anomaly correlation efficiency at 91%.",
                fullContent = """
                    SMARTSHIELD MUNICIPAL DIGEST
                    Date: September 24, 2026
                    Sector: Metropolitan Core & Surrounding Corridors
                    
                    1. INCIDENT METRICS
                    - Total Incidents: 24
                    - Critical Severity: 2 (Industrial chemical vapor leak, Highway 7 gridlock)
                    - High Severity: 6 (Water pressure drop, Power substation surge)
                    - Average Response Dispatch Time: 7.2 minutes (Goal: < 10m)
                    
                    2. CITYPULSE AI SENSOR CORRELATION
                    - Multi-sensor anomaly detections: 9
                    - Highest correlation factor: Precipitation (14mm/h) + Construction bottleneck on Sector 4.
                    - Correlation vs Causation flag applied to 100% of automated alerts.
                    
                    3. CITIZEN IMPACT
                    - Clean air advisories sent: 4,200 residents
                    - Green corridors cleared for EMS: 3 routes
                """.trimIndent()
            ),
            SystemReport(
                id = "REP-2026-0924-B",
                title = "SentinelAPI Threat & Vulnerability Audit",
                category = "SECURITY",
                date = "September 24, 2026",
                summary = "Full penetration audit across 3 municipal API targets. 1 Critical BOLA, 1 Rate-limit flaw identified.",
                fullContent = """
                    SENTINELAPI VULNERABILITY AUDIT REPORT
                    Generated by: Automated API Security Scanner
                    
                    1. AUDITED TARGETS
                    - Municipal Transit & Fleet Gateway (/api/v2)
                    - Citizen Grievance & Service Portal (/api/v1)
                    - Smart Grid & SCADA Telemetry Bridge (/scada/v1)
                    
                    2. KEY FINDINGS
                    - [CRITICAL] API1:2023 Broken Object Level Authorization on /api/v2/vehicles/diagnostics.
                    - [HIGH] API4:2023 Unrestricted Rate Limiting on Citizen Registration endpoint.
                    
                    3. DEADMAN'S DRIVE HARDWARE PROTECTION
                    - FIDO2 USB Security key: CONNECTED & VERIFIED
                    - Immutable cold backup snapshot: SUCCESS
                    - Malicious IPs blocked: 198.51.100.24 (Brute-force session)
                """.trimIndent()
            ),
            SystemReport(
                id = "REP-2026-0924-C",
                title = "Surplus-to-Shelter Food Rescue Impact Summary",
                category = "RESOURCE",
                date = "September 24, 2026",
                summary = "1,240 kg of surplus food diverted to 3 partner shelters. 420 individuals served with zero wastage.",
                fullContent = """
                    SURPLUS-TO-SHELTER RESCUE AUDIT
                    Program: Smart Waste Diversion & Food Security
                    
                    1. RESCUE STATISTICS
                    - Active Donors: 12 (Hotels, Catering services, Supermarkets)
                    - Total Meals Rescued: 420 hot prepared meals
                    - Produce Rescued: 310 kg
                    - Average Match-to-Pickup Time: 28 minutes
                    
                    2. RECIPIENT ALLOCATION
                    - Hope Haven Emergency Shelter: 180 meals
                    - Downtown Community Respite: 140 meals
                    - Eastside Youth Mission: 100 meals
                    
                    3. ENVIRONMENTAL IMPACT
                    - Estimated CO2 emission reduction: 3.1 metric tons
                """.trimIndent()
            )
        )
    }

    Column(
        modifier = modifier
            .fillMaxSize()
            .background(CommandBackgroundDark)
            .padding(horizontal = 16.dp)
    ) {
        Spacer(modifier = Modifier.height(10.dp))

        Row(verticalAlignment = Alignment.CenterVertically) {
            Icon(Icons.Default.Assessment, contentDescription = null, tint = CyanAccent)
            Spacer(modifier = Modifier.width(8.dp))
            Text(
                text = "Command Reports",
                style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold),
                color = TextPrimaryDark
            )
        }
        Text(
            text = "Automated compliance, security and civic operations reports",
            style = MaterialTheme.typography.bodySmall,
            color = TextSecondaryDark
        )

        Spacer(modifier = Modifier.height(14.dp))

        LazyColumn(
            verticalArrangement = Arrangement.spacedBy(12.dp),
            contentPadding = PaddingValues(bottom = 80.dp),
            modifier = Modifier.fillMaxSize()
        ) {
            items(reports.size) { idx ->
                val rep = reports[idx]
                Card(
                    colors = CardDefaults.cardColors(containerColor = CommandCardDark),
                    shape = RoundedCornerShape(12.dp),
                    border = androidx.compose.foundation.BorderStroke(1.dp, CommandBorder),
                    modifier = Modifier
                        .fillMaxWidth()
                        .clickable { selectedReport = rep }
                        .testTag("report_card_$idx")
                ) {
                    Column(modifier = Modifier.padding(14.dp)) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            StatusBadge(text = rep.category, type = "INFO")
                            Text(
                                text = rep.date,
                                style = MaterialTheme.typography.labelSmall,
                                color = TextSecondaryDark
                            )
                        }

                        Spacer(modifier = Modifier.height(6.dp))

                        Text(
                            text = rep.title,
                            style = MaterialTheme.typography.titleSmall.copy(fontWeight = FontWeight.Bold),
                            color = TextPrimaryDark
                        )

                        Text(
                            text = rep.summary,
                            style = MaterialTheme.typography.bodySmall,
                            color = TextSecondaryDark
                        )

                        Spacer(modifier = Modifier.height(8.dp))

                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                text = rep.id,
                                style = MaterialTheme.typography.labelSmall,
                                color = CyanAccent
                            )
                            Text(
                                text = "View Full Report →",
                                style = MaterialTheme.typography.labelSmall.copy(fontWeight = FontWeight.Bold),
                                color = CyanAccent
                            )
                        }
                    }
                }
            }
        }
    }

    // Full Report Modal Dialog
    selectedReport?.let { report ->
        AlertDialog(
            onDismissRequest = { selectedReport = null },
            containerColor = CommandSurfaceDark,
            title = {
                Text(
                    text = report.title,
                    style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                    color = TextPrimaryDark
                )
            },
            text = {
                Surface(
                    color = CommandCardDark,
                    shape = RoundedCornerShape(8.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Text(
                        text = report.fullContent,
                        style = MaterialTheme.typography.bodySmall.copy(fontSize = 12.sp, lineHeight = 18.sp),
                        color = TextPrimaryDark,
                        modifier = Modifier.padding(12.dp)
                    )
                }
            },
            confirmButton = {
                Button(
                    onClick = { selectedReport = null },
                    colors = ButtonDefaults.buttonColors(containerColor = CyanAccent, contentColor = Color.Black)
                ) {
                    Text("Close", fontWeight = FontWeight.Bold)
                }
            }
        )
    }
}
